### ISSUE TITLE
change the title..

### ISSUE THREAD

**Issue by gregorynicholas** [xolvio/rtd#170]
deprecated... ??   changethefucking description of the repo from "the" test runner

**Comment by samhatoum** [comment]
I'm intrigued as to how this 2 year old project is affecting you! Did you search on npm and see a misleading title or something?

**Comment by gregorynicholas** [comment]
LOL.  not a fan of velocity

**Comment by adamdawkins** [comment]
Well, this all seems a little unnecessary...

**Comment by samhatoum** [comment]
@adamdawkins agreed - I was hoping to see what - if anything - needs to change on RTD. Perhaps it's misleading to people searching on NPM. I'll take that as the constructive feedback. Thanks to both
